// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Data;
using MySql.Data.MySqlClient;
using System.Reflection;

namespace serverDS
{
	public class database
	{
		public static void Database(String str)
		{
			str = @"server=localhost;database=dsinnov;userid=root;password=root;";
			MySqlConnection connexion = null;
			
			try
			{
				connexion = new MySqlConnection(str);
				connexion.Open(); //open the connection
			}
			catch (MySqlException err) //We will capture and display any MySql errors that will occur
			{
				Console.WriteLine("Erreur ......... " + err.ToString());
			}
			finally
			{
				if (connexion != null)
				{
					connexion.Close(); //safely close the connection
				}
			}
		}
	}
}

