// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using Gtk;

namespace DSInnovation
{
	public class Interface : Window
	{
		public Interface () : base("PointHair")
		{
			SetDefaultSize(960, 800);
			SetPosition(WindowPosition.Center);

			DeleteEvent += delegate {	Application.Quit();	};

			MenuBar mb = new MenuBar();
			Fixed fix = new Fixed();

			Menu filemenu = new Menu();
			MenuItem file = new MenuItem("File");
			file.Submenu = filemenu;

			MenuItem exit = new MenuItem("Exit");
			exit.Activated += OnFileExited;
			filemenu.Append(exit);

			mb.Append(file);

			Button btn1 = new Button("Ajouter");
			btn1.SetSizeRequest(80, 40);
			Button btn2 = new Button("Modifier");
			btn2.SetSizeRequest(80, 40);
			Button btn3 = new Button("Supprimer");
			btn3.SetSizeRequest(80, 40);

			fix.Put (btn1, 100, 730);
			fix.Put (btn2, 200, 730);
			fix.Put (btn3, 300, 730);

			Add (fix);
			ShowAll();
		}

		void OnDelete(object obj, DeleteEventArgs args)
		{
			Application.Quit();
		}

		void OnFileExited (object obj, EventArgs args) {
			Application.Quit();
		}
	}
}

