// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
namespace DSInnovation
{
	public class personne
	{
		public string nom;
		public string prenom;
		public int points;

		public personne (string nom, string prenom, int points)
		{
			this.nom = nom;
			this.prenom = prenom;
			this.points = points;
		}
	}
}

