// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using MySql.Data.MySqlClient;

namespace serverDS
{
	public class database
	{
		private static MySqlConnection connexion = null;

		public static void Database(String str)
		{	
			try
			{
				connexion = new MySqlConnection(str);	//	On établit une nouvelle connexion à l'hôte correspondant au String str
				connexion.Open(); 					//	On appel la méthode ouvrir la connexion
			}

			catch (MySqlException err) 		//	Récupère l'erreur correspondant à MySql
			{
				Console.WriteLine("Erreur ..................... " + err.ToString());	//	Affiche l'erreur
			}
		}

		public static MySqlConnection GetConnexion{
			get { return connexion; }
		}
	}
}

