// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;

namespace serverDS
{
	class MainClass
	{
		private static bool running;
		
		public static void Main (string[] args)
		{
			running = true;
			new Server();
			
			String str = "server=localhost;database=dsinnov;userid=root;password=root;";

			Console.WriteLine("Connexion établie - " + str);
			database.Database(str);

			Console.WriteLine("Fin de connexion - " + str);
		}
		
		public static bool IsRunning {
			get { return running; }
			set { running = value; }
		}
	}
}
